services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: signup-app
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
        networks:
            - signup-network
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=signup_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
        command: >
            sh -c "./docker/wait-for-it.sh db:3306 -- php artisan migrate && php-fpm"

    nginx:
        image: nginx:alpine
        container_name: signup-nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - signup-network
        ports:
            - "80:80"
        depends_on:
            - app

    db:
        image: mariadb:10.6.0
        container_name: signup-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: signup_db
        volumes:
            - ./docker/db_data:/var/lib/mysql
            - ./docker/mysql.cnf:/etc/mysql/conf.d
        networks:
            - signup-network

networks:
    signup-network:
        driver: bridge
